name: real_estate_ui_tutorial
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  geolocator: ^13.0.4

  image_picker: ^1.0.4
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        
dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  flutter_plugin_android_lifecycle: ^2.0.27
  geolocator_android: ^5.0.1
  leak_tracker: ^10.0.9
  material_color_utilities: ^0.12.0
  vm_service: ^15.0.0
  dart_console: ^4.1.1
  intl: ^0.20.2
  pub_updater: ^0.5.0
